# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wit_imu/lonmsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class lonmsg(genpy.Message):
  _md5sum = "f6d3fea111e2a8e030584cb7b23fbadb"
  _type = "wit_imu/lonmsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float64 orientation_x
float64 orientation_y
float64 orientation_z
float64 orientation_w
float64 angular_velocity_x
float64 angular_velocity_y
float64 angular_velocity_z
float64 linear_acceleration_x
float64 linear_acceleration_y
float64 linear_acceleration_z"""
  __slots__ = ['orientation_x','orientation_y','orientation_z','orientation_w','angular_velocity_x','angular_velocity_y','angular_velocity_z','linear_acceleration_x','linear_acceleration_y','linear_acceleration_z']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       orientation_x,orientation_y,orientation_z,orientation_w,angular_velocity_x,angular_velocity_y,angular_velocity_z,linear_acceleration_x,linear_acceleration_y,linear_acceleration_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lonmsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.orientation_x is None:
        self.orientation_x = 0.
      if self.orientation_y is None:
        self.orientation_y = 0.
      if self.orientation_z is None:
        self.orientation_z = 0.
      if self.orientation_w is None:
        self.orientation_w = 0.
      if self.angular_velocity_x is None:
        self.angular_velocity_x = 0.
      if self.angular_velocity_y is None:
        self.angular_velocity_y = 0.
      if self.angular_velocity_z is None:
        self.angular_velocity_z = 0.
      if self.linear_acceleration_x is None:
        self.linear_acceleration_x = 0.
      if self.linear_acceleration_y is None:
        self.linear_acceleration_y = 0.
      if self.linear_acceleration_z is None:
        self.linear_acceleration_z = 0.
    else:
      self.orientation_x = 0.
      self.orientation_y = 0.
      self.orientation_z = 0.
      self.orientation_w = 0.
      self.angular_velocity_x = 0.
      self.angular_velocity_y = 0.
      self.angular_velocity_z = 0.
      self.linear_acceleration_x = 0.
      self.linear_acceleration_y = 0.
      self.linear_acceleration_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
