// Generated by gencpp from file chassis_drive/Drive.msg
// DO NOT EDIT!


#ifndef CHASSIS_DRIVE_MESSAGE_DRIVE_H
#define CHASSIS_DRIVE_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chassis_drive
{
template <class ContainerAllocator>
struct Drive_
{
  typedef Drive_<ContainerAllocator> Type;

  Drive_()
    : header()
    , angle(0)
    , speed(0)  {
    }
  Drive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _angle_type;
  _angle_type angle;

   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::chassis_drive::Drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_drive::Drive_<ContainerAllocator> const> ConstPtr;

}; // struct Drive_

typedef ::chassis_drive::Drive_<std::allocator<void> > Drive;

typedef boost::shared_ptr< ::chassis_drive::Drive > DrivePtr;
typedef boost::shared_ptr< ::chassis_drive::Drive const> DriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_drive::Drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_drive::Drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_drive::Drive_<ContainerAllocator1> & lhs, const ::chassis_drive::Drive_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle == rhs.angle &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_drive::Drive_<ContainerAllocator1> & lhs, const ::chassis_drive::Drive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_drive::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_drive::Drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_drive::Drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_drive::Drive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_drive::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_drive::Drive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_drive::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20cf24d6503cfee2ffb8f09d5d7a332";
  }

  static const char* value(const ::chassis_drive::Drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20cf24d6503cfeeULL;
  static const uint64_t static_value2 = 0x2ffb8f09d5d7a332ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_drive::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_drive/Drive";
  }

  static const char* value(const ::chassis_drive::Drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_drive::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"int64 angle\n"
"\n"
"int64 speed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::chassis_drive::Drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_drive::Drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_drive::Drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_drive::Drive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_DRIVE_MESSAGE_DRIVE_H
