(cl:in-package wit_imu-msg)
(cl:export '(HEADER-VAL
          HEADER
          ORIENTATION_X-VAL
          ORIENTATION_X
          ORIENTATION_Y-VAL
          ORIENTATION_Y
          ORIENTATION_Z-VAL
          ORIENTATION_Z
          ORIENTATION_W-VAL
          ORIENTATION_W
          ANGULAR_VELOCITY_X-VAL
          ANGULAR_VELOCITY_X
          ANGULAR_VELOCITY_Y-VAL
          ANGULAR_VELOCITY_Y
          ANGULAR_VELOCITY_Z-VAL
          ANGULAR_VELOCITY_Z
          LINEAR_ACCELERATION_X-VAL
          LINEAR_ACCELERATION_X
          LINEAR_ACCELERATION_Y-VAL
          LINEAR_ACCELERATION_Y
          LINEAR_ACCELERATION_Z-VAL
          LINEAR_ACCELERATION_Z
          LON-VAL
          LON
          LAT-VAL
          LAT
))